
services:
  db:
    container_name: psql_dev
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: escolinha_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 34587895
    ports:
      - "5432:5432"
    volumes:
      - pg_data_dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d escolinha_db || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 40      # aumentamos aqui

  pgadmin:
    container_name: pgadmin_dev
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - pgadmin_data_dev:/var/lib/pgadmin

  web:
    container_name: escolinha_dev
    build:
      context: .
    command: [ "sh", "-lc", "chmod +x /scripts/*.sh || true; /scripts/dev.sh" ]
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./scripts:/scripts
    env_file:
      - ./dotenv_files/.env.dev
    depends_on:
      db:
        condition: service_healthy

volumes:
  pg_data_dev:
  pgadmin_data_dev:
